### ISSUE TITLE
Warnning in logs

### ISSUE THREAD

**Issue by sasukebinbin** [wxt9861/esxi_stats#42] opened 2021-01-22 09:57 UTC
**ESXi environment (please complete the following information):**
 - Host/vCenter: [e.g. ESXi 6.7]

**Additional context**
HA logs show :
Logger: homeassistant.util.async_
Source: util/async_.py:105
First occurred: AM12:29:13 (30635 occurrences)
Last logged: PM 5:54:00

Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for esxi_stats doing I/O at custom_components/esxi_stats/__init__.py, line 227: ds_name = ds.summary.name.replace(" ", "_").lower()
Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for esxi_stats doing I/O at custom_components/esxi_stats/esxi.py, line 151: ds_summary = ds.summary
Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for esxi_stats doing I/O at custom_components/esxi_stats/esxi.py, line 162: "connected_hosts": len(ds.host),
Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for esxi_stats doing I/O at custom_components/esxi_stats/esxi.py, line 163: "virtual_machines": len(ds.vm),
Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for esxi_stats doing I/O at custom_components/esxi_stats/esxi.py, line 31: current_session = conn.content.sessionManager.currentSession.key

**Comment by wxt9861** [comment] 2021-02-19 17:28
Duplicate of #35

**Closed by wxt9861** 2021-02-19 17:28 UTC
